name: Build (Bare Metal)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          sudo scripts/install_build_dependencies.sh
          make
          ls -la
      - name: upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output